name: Main Workflow

on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
      - name: pnpm storage cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store/v3
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: pnpm install
        run: pnpm i --frozen-lockfile
      - name: Compile
        run: pnpm run precompile && pnpm run compile && pnpm run postcompile
      - name: Docs
        run: pnpm run docs
      - uses: EndBug/add-and-commit@v7
        with:
          add: docs
          default_author: github_actions
          message: 'docs(): ${{ github.sha }}'
          signoff: true
      - name: SemVer Increment
        id: semver
        run: pnpm run semver
        env:
          GitHubCommits: '${{ toJSON(github.event.commits) }}'
      - uses: EndBug/add-and-commit@v7
        with:
          add: package.json
          default_author: github_actions
          message: 'release(${{ steps.semver.outputs }}): ${{ github.sha }}'
          signoff: true
      - name: Publish to NPM
        run: pnpm publish
